### PR TITLE
cmake: clarify test parallelization

### PR DESCRIPTION
**Pull request by junghans**
To fix over subscribing (see https://github.com/icl-utk-edu/heffte/issues/59#issuecomment-2433138611)

### CODE REVIEW

**Comment by junghans** [comment]
There is also a way to specify the number of GPUs a test needs: https://cmake.org/cmake/help/latest/prop_test/RESOURCE_GROUPS.html

**Comment by mkstoyanov** [comment]
I've looked into the groups but it seems a bit too complicated for heFFTe. Testing does not take long.

How does this PR help? The PROCESSORS property indicates the number of ranks that will be used by the test, provably redundant if RUN_SERIAL is set, but how is it that removing the variable it reduces concurrency?

**Comment by junghans** [comment]
If you run `ctest -jN`, it knows you have `N` cores and with the `PROCESSORS` property `ctest` can then figure out how many jobs to run in parallel.

**Comment by mkstoyanov** [comment]
I misread the PR thinking you are removing the PROCESSORS count.

If you want to skip parallel testing completely,  try `Heffte_SEQUENTIAL_TESTING` we had to do that a while back due to spack setting env variable forcing parallel tests which in turn lead to running out of RAM on a 90+GB GPU.

**Pull request merged**
