### PR TITLE
Added constraint on where ONEAPI backend is tested

### PR DESCRIPTION
**Pull request by G-Ragghianti**

### CODE REVIEW

**Review by mkstoyanov — APPROVED** [review]

**Comment by G-Ragghianti** [comment]
I'll merge once I finish cleaning up the ci matrix logic.

**Comment by G-Ragghianti** [comment]
We still have failure on the ONEAPI backend even when executing on an Intel Xeon CPU.  Thoughts? @mkstoyanov @stomov

**Comment by mkstoyanov** [comment]
Just realized you had a question. The error is `PI_ERROR_DEVICE_NOT_FOUND` which seems like a system setup problem. I don't know if some env variable is missing or something. A standalone install of one-api requires that we source the intel script `setupvars.sh` (or something) in the `/opt/intel/` folder, but I'm not sure how spack does it.

I will be out of town next week, so I will have to work on this later, but I wasn't able to reproduce in the one-api docker container with cmake.

**Comment by mkstoyanov** [comment]
@G-Ragghianti This has been hanging in for a while. Do you wan to close it and maybe reopen later.

**Comment by mkstoyanov** [comment]
Stalled PR, start a new one, if needed.

**Pull request closed without merging**
