### PR TITLE
switch to using openmp target in cmake

### LINKED ISSUE #46: Linking error with fftw3_omp
There is an issue with compiling software on LUMI.

```bash
module load LUMI/23.09 partition/C
module load cray-python cray-fftw
cmake -S heffte-2.4.0-src -B heffte-2.4.0-build -DCMAKE_BUILD_TYPE=Release -D Heffte_ENABLE_AVX=ON -D Heffte_ENABLE_FFTW=ON -D Heffte_ENABLE_PYTHON=ON -D CMAKE_CXX_COMPILER=CC -D MPI_CXX_COMPILER=CC
```

```text
[  1%] Building CXX object CMakeFiles/Heffte.dir/src/heffte_c.cpp.o
[  3%] Building CXX object CMakeFiles/Heffte.dir/src/heffte_plan_logic.cpp.o
[  5%] Building CXX object CMakeFiles/Heffte.dir/src/heffte_magma_helpers.cpp.o
[  6%] Building CXX object CMakeFiles/Heffte.dir/src/heffte_reshape3d.cpp.o
[  8%] Building CXX object CMakeFiles/Heffte.dir/src/heffte_compute_transform.cpp.o
[ 10%] Linking CXX shared library libheffte.so
[ 10%] Built target Heffte
[ 12%] Building CXX object benchmarks/CMakeFiles/convolution.dir/convolution.cpp.o
[ 13%] Linking CXX executable convolution
ld.lld: error: undefined reference due to --no-allow-shlib-undefined: omp_get_thread_num
>>> referenced by /opt/cray/pe/fftw/3.3.10.5/x86_milan/lib/libfftw3_omp.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: omp_get_num_threads
>>> referenced by /opt/cray/pe/fftw/3.3.10.5/x86_milan/lib/libfftw3_omp.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: GOMP_parallel
>>> referenced by /opt/cray/pe/fftw/3.3.10.5/x86_milan/lib/libfftw3_omp.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: omp_get_thread_num
>>> referenced by /opt/cray/pe/fftw/3.3.10.5/x86_milan/lib/libfftw3f_omp.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: omp_get_num_threads
>>> referenced by /opt/cray/pe/fftw/3.3.10.5/x86_milan/lib/libfftw3f_omp.so
```

With a small modification to `FindHeffteFFTW.cmake` the compilation is working:

```cmake
# respect user provided FFTW_LIBRARIES
if (NOT FFTW_LIBRARIES)
    heffte_find_fftw_libraries(
        PREFIX ${FFTW_ROOT}
        VAR FFTW_LIBRARIES
        REQUIRED "fftw3" "fftw3f"
        OPTIONAL "fftw3_omp" "fftw3f_omp" "fftw3_threads" "fftw3f_threads"
                               )
#   if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
#       find_package(OpenMP REQUIRED)
#       list(APPEND FFTW_LIBRARIES ${OpenMP_CXX_LIBRARIES})
#   else()
#       if ("fftw3_omp" IN_LIST FFTW_LIBRARIES)
#           list(APPEND FFTW_LIBRARIES "-lgomp")
#       endif()
#   endif()

    find_package(OpenMP REQUIRED)
    if (OpenMP_FOUND)
        list(APPEND FFTW_LIBRARIES OpenMP::OpenMP_CXX)
    endif()

endif()
```

Before submitting PR, I'd like to understand the rationale behind the if-else and whether it should be fixed in some other way..?

### PR DESCRIPTION
**Pull request by mkstoyanov**
Co-authored-by: ahojukka5@gmail.com

Switch to using OpenMP target inside CMake

closes #46

### CODE REVIEW

**Comment by mkstoyanov** [comment]
@ahojukka5 can you verify that this fixes the issue? I'll merge it as soon as you do.

**Comment by ahojukka5** [comment]
Unfortunately, looks like some more work is still needed.

So yes, the compile error did vanish, so this modification works. But I just noticed that Cmake is finding the wrong compiler (I was a bit wondering already why CMAKE_CXX_COMPILER_ID is GNU ...):

```bash
17:39 $ cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -D Heffte_ENABLE_AVX=ON -D Heffte_ENABLE_FFTW=ON -D Heffte_ENABLE_PYTHON=ON
-- The CXX compiler identification is GNU 7.5.0
...
```

I guess the right compiler should be

```bash
17:44 $ which CC
/opt/cray/pe/craype/2.7.23/bin/CC
✔ ~/dev/heffte/heffte [pr-47 L|✚ 1…1] 
18:33 $ CC --version
Cray clang version 16.0.1  (6d4824324d375100ba18ca639dfc956fe6546d06)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/cray/pe/cce/16.0.1/cce-clang/x86_64/share/../bin
```

So if I compile again, this time with **right** compiler:

```bash
18:34 $ cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -D Heffte_ENABLE_AVX=ON -D Heffte_ENABLE_FFTW=ON -D Heffte_ENABLE_PYTHON=ON -D CMAKE_CXX_COMPILER=CC -D MPI_CXX_COMPILER=CC
-- The CXX compiler identification is Clang 16.0.6
-- Cray Programming Environment 2.7.23 CXX
...
```

We are back in the beginning, or in the "else" part of the if-else branch:

```text
[ 19%] Linking CXX executable convolution
ld.lld: error: undefined reference due to --no-allow-shlib-undefined: omp_get_thread_num
>>> referenced by /opt/cray/pe/fftw/3.3.10.5/x86_milan/lib/libfftw3_omp.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: omp_get_num_threads
>>> referenced by /opt/cray/pe/fftw/3.3.10.5/x86_milan/lib/libfftw3_omp.so
```

However, if I add, as you proposed:

```cmake
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU" OR "${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang") ...
```

It will actually compile. Can you clarify, what you mean by writing

> ... enabling OpenMP for clang will use the Intel libiomp symbols while FFTW will require the libgomp symbols

? This is just a suggestion, but could this issue be solved by having a separate option to choose whether to use OpenMP or not. And if this option is not **explicitly set**, then string comparison is used to determine the correct usage (in automatic manner)? So we could have something like

```cmake
# respect user provided FFTW_USE_OPENMP
if (NOT DEFINED FFTW_USE_OPENMP)
    message(STATUS "FFTW_USE_OPENMP is not defined, will search for OpenMP if CMAKE_CXX_COMPILER_ID is GNU")
    if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
        message(STATUS "CMAKE_CXX_COMPILER_ID is GNU, will search for OpenMP")
        set(FFTW_USE_OPENMP TRUE)
    else()
        message(STATUS "CMAKE_CXX_COMPILER_ID is not GNU, will not search for OpenMP")
        set(FFTW_USE_OPENMP FALSE)
    endif()
else()
    message(STATUS "FFTW_USE_OPENMP is defined, will search for OpenMP if FFTW_USE_OPENMP is TRUE")
    message(STATUS "FFTW_USE_OPENMP = ${FFTW_USE_OPENMP}")
endif()
```

and

```cmake
...
    if (FFTW_USE_OPENMP)
        find_package(OpenMP REQUIRED)
        list(APPEND FFTW_LIBRARIES OpenMP::OpenMP_CXX)
    else()
...
```

**Comment by mkstoyanov** [comment]
I think we are converging to the solution here.

GNU compilers use libgomp.so for OpenMP while Clang uses libiomp.so

The question is which compiler was used for libfftw_omp. On the Cray machine that you have, I suppose they used their own Cray compiler, hence using the Clang OpenMP version works just fine.

The latest commit that I pushed will always assume that if `fftw_omp` is present then it is using the OpenMP from the same CXX compiler. I added an option that will override that and allow to manually select the library and mix-and-match between the compilers.

**Comment by mkstoyanov** [comment]
> I confirm that this is now compiling in the Cray environment. But is this now also changing the default behavior of Cmake file? The consequence would be that e.g. before mentioned ROCm clang compiler users need to explicitly define `-lgomp` from now on to compile software.

Doing a mix-and-match between the compilers should be treated as the exception rather than the rule. I tested on a docker environment and Ubuntu seems to pickup the correct dependencies even without the `-lgomp`. I don't even remember who reported this long time ago but I'm sure it was on some exotic system.

**Review by ahojukka5 — APPROVED** [review]
LGTM

**Pull request merged**
